
CREATE TABLE IF NOT EXISTS tour_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  departure_id BIGINT UNSIGNED NOT NULL,
  day_number INT NOT NULL DEFAULT 1,
  note TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (departure_id) REFERENCES departure_schedules(id) ON DELETE CASCADE
) ENGINE=InnoDB;
